[DB]
# Cadena de conexión ODBC para SQL Server
connection_string = DRIVER={ODBC Driver 17 for SQL Server};SERVER=localhost;DATABASE=Test;Trusted_Connection=yes;

[APP]
log_file = log_asignacion_conductores.log
liberacion_horas = 1.5
assignments_table = asignaciones_grupos
force_table_recreate = True

[CONDUCTORES]
# Configuración para asignación de conductores aleatorios
cantidad_aleatoria = 5
nombre_prefijo = Conductor
apellido_prefijo = Test
incluir_dni = True
tipos_licencia = A,B,C
plazas_vehiculo = 4,20,55
activo_por_defecto = True
